### ISSUE TITLE
Column index is off by one

### ISSUE THREAD

**Issue by jdkato** [TimKam/atomic-vale#4]
I noticed that the column index is one higher than it should be. For example, a Markdown document with the following text:

```
This is a very interesting sentence!
```

yields

```
example.md:1:11:vale.Editorializing:Consider removing 'very'
```

from Vale, but I get `1:12` in Atom.

I think the issue is that Atom's [columns](https://atom.io/docs/api/v1.5.0/Point#instance-column) are zero-indexed. So, 

```js
range: [
    [atomMessageLine, message.Span[0] - 1]
    [atomMessageLine, message.Span[1]]
]
```
 should fix it.

Thanks for your work on this plugin!

**Comment by TimKam** [comment]
Thanks for reporting. Seems that it occurs since 1.1 release. Will fix it asap.

**Comment by TimKam** [comment]
Actually, I consider the difference and set `atomMessageLine = message.Line - 1`. I also can't reproduce the issue locally.

**Comment by jdkato** [comment]
Hmm, that's interesting. For what it's worth, here's what I'm seeing (on v1.2.0 and Vale 0.4.0):

![demo](https://cloud.githubusercontent.com/assets/8785025/24929867/607cb982-1ebc-11e7-90fc-091c78be127c.png)

(Note that the "v" in "very" isn't underlined and the location is 1:12.)

**Comment by TimKam** [comment]
Sorry, my bad. I was looking and the line index. Thanks!
